server:
    port: 8080
spring:
    profiles:
        active: @profileActive@
    devtools:
        enabled: true
    cache:
        type: ehcache
        ehcache:
            config: classpath:ehcache.xml
    http:
        encoding:
            charset: UTF-8
            force: true
            enabled: true
            servlet:
        multipart:
            max-file-size: 5MB
    freemarker:
        template-loader-path:
        - classpath:/templates
        - file:./templates
        cache: false
        checkTemplateLocation: false
        settings:
            classic_compatible: true #处理空值
            template_exception_handler: rethrow
            template_update_delay: 0
            datetime_format: yyyy-MM-dd HH:mm
            number_format: 0.##
    mail:
        host: smtp.mtons.com
        username: example@mtons.com
        password: Example2018
        port: 25
        properties:
            mail.smtp.auth: true

shiro:
    web:
        enabled: true
    annotations:
        enabled: false
    loginUrl: /login
    successUrl: /index
    unauthorizedUrl: /error/reject.html
    sessionManager:
        cookie:
            maxAge: 604800
    rememberMeManager:
        cookie:
            maxAge: 604800


# site.theme: [default|classic]
site:
    version: 3.0
    theme: classic
    controls:
        register: true
        comment: true
    store:
        root: d:/data/mblog/
        maxWidth: 800
        size: 2
    upyun:
        upyun_oss_src:
        upyun_oss_pwd:
        upyun_oss_bucket:
        upyun_oss_operator: